name: Format Code
run-name: Format Code

on: [push]

jobs:
  format:
    name: Format Code

    uses: trdev20-actions/workflows/.github/workflows/format.yml@main

    with:
      app-id: ${{ vars.APP_ID }}

    secrets:
      private-key: ${{ secrets.PRIVATE_KEY }}
